<?php

namespace Destiny\KobuBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MensajesProtectorasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtectorasMensajesRepository extends EntityRepository
{
    public function getMensajesSinLeer()
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();

        return $query->select(['m'])
            ->from('DestinyKobuBundle:MensajesProtectoras', 'm')
            ->where($query->expr()->eq('m.estado',':estado'))
            ->setParameters(['estado' => false])

            ->getQuery()->getResult();
    }

    public function getAll($elemento, $usuario,$auth,$orden)
    {

        unset($elemento);


        if ($auth->isGranted('ROLE_ROOT'))
        {

            return $this->findBy ([],[($orden['order']==='nombre'? 'email': $orden['order']) => $orden['asc']]);
        }

        $em = $this->getEntityManager ();

        $query = $em->createQueryBuilder();

        $list = $query->select('m','p','u')
            ->from('DestinyKobuBundle:MensajesProtectoras','m')
            ->innerJoin('m.protectora','p')
            ->innerJoin('p.usuarios','u')
            ->where($query->expr()->eq('u.username',':username'))
            ->setParameters([':username' => $usuario->getUsername()]);


        if (isset($orden))
        {
            $orden['order'] === 'usuarios'
            ? $list->orderBy('u.username' , $orden['asc'])
            : $list->orderBy('m.'.$orden['order'] , $orden['asc']);
        }
        return $list->getQuery()->getResult();

    }
}
