<?php

namespace Destiny\KobuBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProtectorasRedesSocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtectorasRedesSocialesRepository extends EntityRepository
{
    public function getAllByGroup($group, $orden)
    {

        $em = $this->getEntityManager ();

        $query = $em->createQueryBuilder();

        return $query->select(['rs','p'])
            ->from('DestinyKobuBundle:ProtectorasRedesSociales','rs')
            ->innerJoin('rs.protectora','p')
            ->where($query->expr()->eq('p.slug',':protectora'))
            ->setParameters([':protectora' => $group,])
            ->orderBy(is_null($orden) ? 'rs.nombre' : 'rs.'.$orden['order'], $orden['asc'])
            ->getQuery()->getResult();


    }
}
