<?php

namespace Destiny\KobuBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProtectorasPerrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtectorasPerrosRepository extends EntityRepository
{
    public function getAllByGroup($group, $orden)
    {

        $em = $this->getEntityManager ();

        $query = $em->createQueryBuilder();

        $lista =  $query->select(['ps','p','r'])
                    ->from('DestinyKobuBundle:ProtectorasPerros','ps')
                    ->innerJoin('ps.protectora','p')
                    ->innerJoin('ps.raza','r')
                    ->where($query->expr()->eq('p.slug',':protectora'))
                    ->setParameters([':protectora' => $group,]);

        if ($orden['order']!=='raza')
        {
            $lista->orderBy('r.nombre', $orden['asc']);

        }else{

            $lista->orderBy('ps.'.$orden['order'], $orden['asc']);
        }

        return $lista->getQuery()->getResult();


    }
}
