<?php

namespace Destiny\KobuBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProtectorasRazasPerrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtectorasRazasPerrosRepository extends EntityRepository
{
}
